PREFIX chembl: <http://rdf.ebi.ac.uk/terms/chembl#> 

SELECT (COUNT(DISTINCT ?molecule) as ?total_count)
FROM <http://rdf.integbio.jp/dataset/togosite/chembl>
WHERE {
  ?molecule chembl:atcClassification ?atc .
}
