PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX pdbo: <https://rdf.wwpdb.org/schema/pdbx-v50.owl#>
PREFIX taxid: <http://identifiers.org/taxonomy/>

SELECT (COUNT(DISTINCT ?pdb) AS ?total_count)
FROM <http://rdf.integbio.jp/dataset/togosite/pdbj>
WHERE {
  ?pdb a pdbo:datablock ;
      pdbo:has_entity_polyCategory/pdbo:has_entity_poly/rdfs:seeAlso ?uniprot_link ; #DNAのentryを排除
      pdbo:has_entityCategory/pdbo:has_entity/rdfs:seeAlso taxid:9606 .
}
