#!/usr/bin/env spang2
# @endpoint https://integbio.jp/togosite/sparql
# @option --time

PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX taxid: <http://identifiers.org/taxonomy/>

SELECT (COUNT(DISTINCT ?enst) AS ?total_count)
FROM <http://rdf.integbio.jp/dataset/togosite/ensembl>
WHERE {
  ?enst obo:SO_has_part ?exon ;
      obo:SO_transcribed_from ?ensg .
  ?ensg obo:RO_0002162 taxid:9606 . # in taxon
}
